apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saywhat-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamNoah1/argo-aks-poc
    path: chart
    targetRevision: "1.0.0"
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    name: bps-ms-conhub-aks-01
    namespace: gitops-test