apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saywhat-app-prod
  namespace: argocd
spec:
  project: default
  source:
    chart: saywhat-chart
    repoURL: registry-1.docker.io/iamnoah4real
    targetRevision: "0.1.0"
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    name: bps-ms-conhub-aks-01
    namespace: gitops-test