apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saywhat-app-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: saywhat-chart
    repoURL: registry-1.docker.io/iamnoah4real
    targetRevision: "1.0.0"
    helm:
      valueFiles:
      - values-dev.yaml
      values: |
        image:
          tag: "1.0.1"
  destination:
    name: bps-ms-conhub-aks-01
    namespace: gitops-test